[project]
name = "modelcontainer"
authors = [{name = "BytePengwin"}]
version = "0.1.0"
description = "Simple container for langchain models"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.1.0",
    "langchain-openai>=1.1.0"
]
